### ISSUE TITLE
RTL8710 support

### ISSUE THREAD

**Issue by Kenzu** [eerimoq/simba#105]
Hey

Is it posible to port simba\pumbaa to the new RTL8710 wifi chip?

http://www.cnx-software.com/2016/07/28/an-alternative-to-esp8266-realtek-rtl8710-arm-cortex-m3-wifi-iot-modules-sell-for-2-and-up/

http://www.cnx-software.com/2016/08/01/development-resources-for-realtek-ameba-rtl8710-rtl8711-and-rtl8195-wifi-socs/ 

Thanks

**Comment by eerimoq** [comment]
I've never heard of this chip before, but it certainly looks interesting.

It's certainly technically possible to port Simba/Pumbaa to this chip, but it would probably require contributions from someone but me at the moment. I neither own the board, nor have any immediate interest in investing time into it. If you are want to start yourself I'll gladly answer questions and provide guidance where needed.

ARM chipsets are already supported by Simba/Pumbaa, the big question is what it takes to make WiFi work. What libraries are required? What can/should be implemented from scratch? I've absolutely no idea. If you want this port to happen I think you have to create a fork and show some skills implementing it =)

...but... as I know myself... I probably cannot resist digging into it myself... just have to order a board... but any help would be welcome =) I won't promise anything.. =)
