### ISSUE TITLE
PlatformIO Simba and Wemos Lolin32

### ISSUE THREAD

**Issue by f0m3** [eerimoq/simba#107]
When i try to build the examples on platformio i get a
```
Environment arduino_mega        [SUCCESS]
Environment arduino_uno         [SUCCESS]
Environment arduino_nano        [SUCCESS]
Environment espressif_esp12e    [SUCCESS]
Environment lolin32             [ERROR]
========================== [ERROR] Took 75.87 seconds ==========================
```

and:
```
Archiving .pioenvs/lolin32/libFrameworkArduinoVariant.a
src/main.c:31:19: fatal error: simba.h: No such file or directory
compilation terminated.
Indexing .pioenvs/lolin32/libFrameworkArduinoVariant.a
*** [.pioenvs/lolin32/src/main.o] Error 1
Compiling .pioenvs/lolin32/FrameworkArduino/Esp.o
```
I guess it would be possible to build but i need a hint because i just switched from arduinoIDE to platformIO... 
I was able to build a blink example without simba und upload it to the lolin32 with platformIO.

**Comment by eerimoq** [comment]
What does platformio.ini look like?

Try this configuration:

```
[env:nano32]
platform = espressif32
framework = simba
board = nano32
```

The Wemos Lolin32 is not supported by Simba as of today. Would probably be easy to add, but I'm quite sure you can use the nano32 board instead. The MCU is the same on the two boards, and ESP32, right?

**Comment by simonlbn** [comment]
For whatever it's worth, I ordered a WEMOS LOLIN32 when they were released and expect to add support for it to Simba when it arrives at some point (standard shipping from China to Europe... takes a while).

On a general note, it is another ESP32 based board with 4MB flash, so I would expect most things to work with one of other ESP32 board specification like eerimoq mentions.

**Comment by f0m3** [comment]
I ordered one lolin32 from aliexpress 2 weeks ago and yesterday it arrived in Germany. I was impressed! :-) 
Building worked with 
```
[env:nano32]
platform = espressif32
framework = simba
board = nano32
```
I will try to upload tomorrow and report! Thanks for the help.

**Comment by f0m3** [comment]
I changed &pin_led_dev to &pin_gpio05_dev in the simba/blink example and it worked! Thanks for the help!

**Comment by eerimoq** [comment]
I updated the [porting documentation](http://simba-os.readthedocs.io/en/latest/developer-guide/porting.html) with more details on how to add a new board. Have a look there, and start be copying files from an existing ESP32 board, for example the Nano32.
