### ISSUE TITLE
MQTT Last Will and Testament

### ISSUE THREAD

**Issue by erenfro** [eerimoq/simba#109]
MQTT supports a feature called "Last Will and Testament". This is basically a client initiated, server-maintained negotiation of sorts. Essentially a topic/payload is provided in the case the mqtt client disconnects without negotiating the disconnection, such as in the case of a dropped connection, failure, network interruption, etc. 
After reviewing the mqtt_client.c code, I did not see any facilities for sending this last will feature. But everything else looks pretty feature complete more so than most embedded mqtt libraries I've seen. (very impressed!)

**Comment by eerimoq** [comment]
Ohh okay, I didn't know about that feature. Would it be easy to add?

**Comment by simonlbn** [comment]
I looked a bit into this, "unfortunately" the Last Will and Testament is sent to the MQTT broker at connection time, so the current Simba mqtt_client API has to be adjusted a bit to support that. It might make sense to do at the same time as a few other changes such as splitting init and start of driver.

**Comment by eerimoq** [comment]
Feel free to make any changes, but of course, keep non-backwards compatible changes to a minimum to minimize the impact on any users.
