### ISSUE TITLE
MQTT authentication

### ISSUE THREAD

**Issue by erenfro** [eerimoq/simba#110]
The mqtt lacks the ability to authenticate to an mqtt server via username/password. For use in more sensitive situations, authentication may be needed to connect to an mqtt (or mqtts) server with authentication before it can proceed to communicate. Since MQTT is used often in IoT projects that may involve security sensitive situations, such as lock controls, door controls, etc, authentication is definitely strongly recommended.

**Comment by eerimoq** [comment]
I've not used MQTT myself mor ethan in theory designing the MQTT module, and my approach was that the connection will be encrypted by SSL/TLS anyway, so a username/password would not be important to ensure data integrity. Anyway, I guess many brokers requires username/password, so it has to be implemented anyway. I'll not have time to implement it in the near future, sorry.

**Comment by simonlbn** [comment]
I will need MQTT authentication for my current project, but no guarantees for when I will get to it.

**Comment by simonlbn** [comment]
A small status update: I got the code to support authentication and last will and testament, and I'm not working on testing it and writing unit tests.
