### ISSUE TITLE
ESP: I2C module.

### ISSUE THREAD

**Issue by eerimoq** [eerimoq/simba#12]
Implement the I2C module for the ESP.

**Comment by eerimoq** [comment]
Software i2c implemented as no hardware i2c seems to be available.

**Comment by rahuldeo2047** [comment]
I am evaluating Simba OS for my pet project. Simba framework seems easy enough to implement.
However, I came across an issue where read part is not working.

ESP8266 I2C module read is not working.

https://github.com/rahuldeo2047/ESP_rtos_eval/blob/master/simba/i2c/sensors/lib/mpu6050_basic/mpu6050_basic.c#L198

Please ignore the coding standard.
