### ISSUE TITLE
ESP32: update wifi lib

### ISSUE THREAD

**Issue by LupascuAndrei** [eerimoq/simba#124]
I see that simba is currently using an older version of https://github.com/espressif/esp32-wifi-lib
Espressif release notes mention many fixes regarding wifi crashes and issues in the latest esp32 wifi lib.
https://github.com/espressif/esp-idf/releases
After making some stress tests with esp-idf 2.0 (Later Edit: 2.1), i see that sockets have never been temporarily blocked and ssl handshakes never fail because of timeouts ( using this example https://github.com/espressif/esp-idf/tree/master/examples/protocols/https_request )
These issues can be reproduced inside simba and i think it's because of the outdated wi-fi lib.
Is there a straight forward way to update only the wifi libs inside simba?
Thank you in advance.

**Comment by eerimoq** [comment]
Hi,

ok, nice catch, I'll make an uplift to version 2.0 soon. Hopefully Espressif hasn't done too many non-backwards compatible changes. =)

**Comment by LupascuAndrei** [comment]
That's great, thank you for the quick response ! 

Can it be an uplift to 2.1 since it was merged recently into master?
I managed to reproduce the issues on 2.0, but not on 2.1.

**Comment by eerimoq** [comment]
I started the ESP-IDF uplift, but facing some problems with system startup on v2.1 and sockets v2.0. Will give an update here when I know more about the problems.

**Comment by LupascuAndrei** [comment]
Please let me know if there's anything i can help with, i'll gladly do my best
