### ISSUE TITLE
ADC conversion from ISR

### ISSUE THREAD

**Issue by wingstar74** [eerimoq/simba#13]
One sample is enough.

**Comment by eerimoq** [comment]
Implemented for AVR in 26f4dba2dbeeeba58a121e66b7e57506b64f497f.

**Comment by wingstar74** [comment]
Whee, thanks, will try it out.

**Comment by eerimoq** [comment]
I implemented a test in tst/drivers/adc that uses both adc_convert() and adc_convert_isr(). Pin D2 should be connected to A0 for the test to work.

**Comment by wingstar74** [comment]
When calling the adc_init, does it matter what sample rate you set when using the adc_convert_isr()?

**Comment by eerimoq** [comment]
No, the the sampling rate is not used in the ISR function.
