### ISSUE TITLE
App name with platformio

### ISSUE THREAD

**Issue by shacal** [eerimoq/simba#131]
Hmm, did not find any way to define APP_NAME variable with platformio.

PS: Love this RTOS, working with KNX, Hitachi LCD with I2C and some Oled displays.
Will provide pull's for drivers and clients at some point :)

**Comment by eerimoq** [comment]
This is what it looks like in the Sconscript that PlatformIO uses to build a Simba appliation: https://github.com/eerimoq/simba/blob/master/make/platformio.sconscript#L3963-L3964

Unfortunately I don't know how to set a variable in the Scons environment, I only use the GNU Make based build system, which I know much better.

You can of course modify the application name in the Sconscript, but it's a system wide change of course.

Lovely, more drivers are always welcome! =)

And, no, parity and bit settings are not part of the UART driver API, and not in the code either. Can be added of course. Any suggestions on what the API should be?

**Comment by shacal** [comment]
Yeh, I think problem is Scons... maybe for backdoor is to check root of app and read APP.txt and name from there... of have an config that defines name. app_name in sysinfo is kinda "ugly" 🗡 

For parity, I currently have own function uart_start_config(*uart, int baud, int parity, int eq)

and then have parity defined with UART_8N1  etc like SERIAL_XXX in arduino framework.
Personally, I think uart_init should have config variable as uart_init(struct uart_driver_t *self_p, struct uart_device_t *dev_p, long baudrate, int config, void *rxbuf_p, size_t size)

**Comment by shacal** [comment]
Hmm, and just after post I remembered that not all chips support configuration and always use 8N1.
Maybe have uart_configure(config) to have default (8N1) and port will give build error as not supported :)

**Comment by eerimoq** [comment]
Yeah, and changing ``uart_init()`` would break backwards compatibility. An alternative is to add ``uart_set_*()`` functions for additional initialization of the UART object, which takes effect when ``uart_start()`` is called. For example, ``uart_set_parity(int parity)``.

**Comment by shacal** [comment]
Created new issue for uart parity.
Let's keep this for app name.

**Comment by rafacouto** [comment]
Just commited PR #133 in order to use APP_NAME variable from the environment. It is another way to define the application name different from checking a file from sources directory (as @shacal suggests) but less intrusive and easy to implement in _platformio.sconscript_.

**Comment by shacal** [comment]
This was my first implementation also, but for platformio and multiple platforms (like windows) it is pain.
Bud id say good addition!

Remo Kallio
________________________________

**Comment by eerimoq** [comment]
In PlatformIO 3.4.1 the application name can be set in an ``extra_script``, without too much trouble.

**platformio.ini**

```
[env:arduino_uno]
platform = atmelavr
framework = simba
board = uno
extra_scripts = config.py
```

**config.py**

```
Import('env')

# Set the Simba application name.                                                                                                                                  
env.Replace(NAME='MyApplicationName')
```

**Comment by shacal** [comment]
Good catch, not using 3.4.1 yet 🙈

Remo Kallio
________________________________

**Comment by eerimoq** [comment]
Anything stopping you? =)

**Comment by shacal** [comment]
Nope, updating later tonight. 🙈

**Comment by eerimoq** [comment]
=P

**Comment by eerimoq** [comment]
Let me know if it works as expected. If it does, I'll add it to the documentation.

**Comment by rafacouto** [comment]
@eerimoq Well, extra_script seems a better solution. Anyway, patch #133 is not intrusive and it also works in the case of _NAME_ is not defined (at least in command line environments; I don't know if it works in click-windowed OS's) :wink:

**Comment by eerimoq** [comment]
Yeah, Windows sucks for programmers =)

BTW, ``platformio.sconscript`` is a generated file. Edit ``make/platformio/platforimio.py`` instead and I can accept the pull request.

**Comment by shacal** [comment]
config.py works with win, mac and ubuntu 👍

**Comment by eerimoq** [comment]
Wonderful! Thanks for testing! =P

**Comment by eerimoq** [comment]
I added a section in the documentation: http://simba-os.readthedocs.io/en/latest/user-guide/build-system.html#platformio
