### ISSUE TITLE
Master branch breaks linker with platformio

### ISSUE THREAD

**Issue by shacal** [eerimoq/simba#135]
Using latest master with platformio and seems that something is broken.
Release version works fine, but switching to master missing some references src/oam/console.c:61: undefined reference to `uart_start'

This happens in macOS, not tested others yet.

**Comment by eerimoq** [comment]
``platformio.sconscript`` is a generated file that has not been generated recently. There is probably some inconsistency that a regeneration will solve.

``make platformio`` generates the file, but it requires the Simba build system to work, including toolchains.

**Comment by shacal** [comment]
Oh, yeh, you moved drivers to subfolders.
scon can't find all files anymore :D

**Comment by eerimoq** [comment]
Lol yeah that's it =)

I can generate a new one tonight if you havn't already generated one.

**Comment by shacal** [comment]
Can't generate now, as mac make fails on me... cglang problem with stdio.h :(

**Comment by eerimoq** [comment]
Pushed a fix.

**Comment by shacal** [comment]
Cool, I try to test asap.

**Comment by shacal** [comment]
A, btw any milestone for next release for platformio?
Build machines and auto deploy machines run PIO to build, test and publish... did not get any easy way to hack github version in :(

**Comment by eerimoq** [comment]
Not sure, a few new drivers, NMEA sentence parser, probably some bug fixes, nothing major I think.

**Comment by shacal** [comment]
Id like to include uart config with avr in that list :P

**Comment by eerimoq** [comment]
Sure, if it is ready =)

**Comment by eerimoq** [comment]
Ohh, there is a major change for AVR. The system tick uses a 16 bits hardware timer instead of 8 bits. So if someone is using that timer they'll be mad.

**Comment by shacal** [comment]
I'm 🗡 
:P

**Comment by eerimoq** [comment]
What do you mean??? =)

**Comment by shacal** [comment]
Works with latest pull
