### ISSUE TITLE
Pin assigment for UART in ESP32

### ISSUE THREAD

**Issue by rafacouto** [eerimoq/simba#137]
Currently, [pin assignment for second and third UART in ESP32 port](https://github.com/eerimoq/simba/blob/master/src/mcus/esp32/mcu.c#L86-L123) are these ones:
- UART 1: TX=gpio19 RX=gpio23
- UART 2: TX=gpio18 RX=gpio05

However, according to the datasheet, the alternate functions of pins ([Technical Reference Manual](https://espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf), 4.10 IO_MUX Pad List) should be:
- UART 1: TX=gpio10 RX=gpio09
- UART 2: TX=gpio17 RX=gpio16

Moreover, published pinout diagrams like ![wroom32](https://cdn-shop.adafruit.com/product-files/3269/pinout_wroom_pinout.png) show gpio10,09 and gpio17,16 as TX,RX for u1 and u2.

Is the current code right? Should it be changed?

**Comment by eerimoq** [comment]
I see no reason not to change it to match the pinout picture. I think the UART driver and pin mapping was implemented before that picture was published, so I just picked pins randomly. Can't remember exactly...
