### ISSUE TITLE
AVR: Timing & Time

### ISSUE THREAD

**Issue by shacal** [eerimoq/simba#142]
Hey!

Im having a lot of issues with AVR and it's time.
Both of the examples gives various results and also time and timing is off by far. Enabling threads, and we are way more off the time table.

```
static unsigned long micros()
{
  static struct time_t t;
  time_get(&t);
  return (t.seconds * 1000000) + (t.nanoseconds / 1000L);
}

static unsigned long millis()
{
  return micros() / 1000L;
}

int main()
{
  sys_start();

  unsigned long nowTimeMicros = 0;
  unsigned long lastSecondMicros = 0;

  while (1)
  {
    nowTimeMicros = micros();
    if ((nowTimeMicros - lastSecondMicros) >= 1000)
    {
      lastSecondMicros = nowTimeMicros;
      std_printf(OSTR("second %d\r\n"), nowTimeMicros);
    }
  }

  return 0;
}
```

and

```
int main()
{
  sys_start();

  unsigned long nowTimeMicros = 0;
  unsigned long lastSecondMicros = 0;

  while (1)
  {
    nowTimeMicros = time_micros();
    if ((nowTimeMicros - lastSecondMicros) >= 1000)
    {
      lastSecondMicros = nowTimeMicros;
      std_printf(OSTR("second %d\r\n"), nowTimeMicros);
    }
  }

  return 0;
}
```

**Comment by eerimoq** [comment]
An integer is 16 bits on AVR, so multiplying by 100000 will overflow the variable.

The documentation of `time_micors()` should be improved to more clearly describe that the function wraps very quickly, often it wraps every system tick, which is about 10 ms.

**Comment by shacal** [comment]
Is there then any good way to measure micros and millis?
I have protocol that hat 2-2.5ms EOP and I have hard time to match that receive time.
Quick mahsup with micros() and millis() with arduino works 99%, with simba I get less than 10% EOPs.
I have tested time_get(), time_XX with and without allocation of time_t, static time_t etc blocks. But can't get accurate timing in any means.
Would it be best to implement knrl_ticks(), krnl_micros() and krnl_millis() with proper scalers and types that do not wrap and does not affect sys_lock() etc.
Even the sys_uptime() gives me some weird values and jumps.

**Comment by eerimoq** [comment]
Try to use long instead of int in your first example, and multiply by 1000000, not 100000.

**Comment by shacal** [comment]
Sorry, code was written from memory so numbers are bit off... <have to fix them>.
But, i noticed possible problem. I have 2ms requirement, but then i do thrd_sleep_us(400) - to give other task time, that sleep makes me skew 19000us before continue of execution in same thread.
And this is with MEGA2560... tiny is over 28000us (makes sense as it is 8Mhz)...
So can allocating time_t and creating timer for thread take so much time and skew thread, but not affect other threads?

Just wanna speculate first, before deep diving to debug avr code 💯

**Comment by eerimoq** [comment]
Timers started with `thrd_sleep_us()` are evaluated every system tick. So it the tick is 20 ms, the resolution is 20 ms.

**Comment by shacal** [comment]
Hmm, makes sense.
I need to investigate this a bit more, as currently to get accurate timing below 20ms is unstable with avr. Specially if trying to resolve them isr level. I might just hack AVR specific for now and test out hardware timers...

I think having micros() and millis() from hardware is essential for micro controller for timing, but 20ms resolution works for most cases.

**Comment by eerimoq** [comment]
I think `sys_uptime()` on AVR will give a high resolution correct time. `time_get()` calls `sys_uptime()`, so they are pretty much the same. What went wrong using `time_get()`? Can you share the output?

**Comment by shacal** [comment]
What would be the best way in driver to monitor uart interop interval then?

So, driver is attached to UART and protocol defines 2-2.5ms delay as EOP.
Now, one way to implement driver is to create thread, that checks uart queue size and reads from there and outputs in own queue all messages that we wanna expose from network, but internally also registers state changes, reset calls (and optional interop pin). Using time here, like millis() defined on ticket description, gives various result. Uppin system tick speed fixes this in some level.
But then again, system speed should not be relevant here... as UART is interop driven, having driver more access to that state, allowing to read tick time in interop so driver can write EOP to the output queue.

This is also kind of design question, as driver with 2 or more threads I think is bad...
Poll is bad, as data size varies and data input rate is based on network and we have to respond ACK or NACK in certain time on receive of EOP etc... callback vs poll (too late to ACK).

Have ported this to linux kernel and in arduino etc... but somehow can't wrap my head around in simba :D

Also lookin example drivers, there is callbacks and polling variations. But hard to decide what should low level driver implement.

**Comment by eerimoq** [comment]
Is there a datasheet of the device I can read?

**Comment by shacal** [comment]
Here: http://www.hqs.sbt.siemens.com/cps_product_data/gamma-b2b/TPUART2_technical-data.pdf

**Comment by shacal** [comment]
Used hardware timers on AVR made this AVR specific driver.
