### ISSUE TITLE
ESP8266: nvm not working

### ISSUE THREAD

**Issue by YegorBobrovski** [eerimoq/simba#146]
Running nvm example project on ESP8266 12E throws lot of errors in output. It starts from failed nvm mounting.

On [forum](https://forum.simbaos.org/showthread.php?tid=17&pid=54#pid54) @eerimoq mentioned that it might be a need of nvm configuration. So, which part of code configures it?

**Comment by eerimoq** [comment]
Configuration variables that starts with `CONFIG_NVM_`.

These two files contains most of the NVM and emulated EEPROM:

https://github.com/eerimoq/simba/blob/master/src/oam/nvm.c
https://github.com/eerimoq/simba/blob/master/src/drivers/storage/eeprom_soft.c
