### ISSUE TITLE
DHT Modul not working at all

### ISSUE THREAD

**Issue by feugen** [eerimoq/simba#148]
Hey guys,

I got an Arduino UNO and my editor is Atom (PlatformIO).
I tired to run the blink example and it works for me but I cant run any dht functions. I tried to run this example: https://github.com/eerimoq/simba/blob/master/examples/dht/main.c

and it gives me: 
`
- Error	GCC	aggregate 'main()::dht_driver_t dht' has incomplete type and cannot be defined

- Error	Build	error: aggregate 'main()::dht_driver_t dht' has incomplete type and cannot be defined

- Error	GCC	'dht_module_init' was not declared in this scope

- Error	Build	error: 'dht_module_init' was not declared in this scope

- Error	GCC	'dht_init' was not declared in this scope

- Error	Build	error: 'dht_init' was not declared in this scope

- Error	GCC	'dht_read' was not declared in this scope

- Error	Build	error: 'dht_read' was not declared in this scope

- Error	GCC	'errno_as_string' was not declared in this scope

- Error	Build	error: 'errno_as_string' was not declared in this scope
`

It looks like its not enough just to import simba.h. :-/
So I downloaded dht.c and dht.h and included to my project, and I still got 

- Error	GCC	'errno_as_string' was not declared in this scope

So I removed this part of the code. But then I still  get: 

.pioenvs/uno/src/main.o: In function `main':
```
../src/main.cpp:22: undefined reference to `dht_module_init()'
../src/main.cpp:26: undefined reference to `dht_init(dht_driver_t*, pin_device_t*)'
../src/main.cpp:43: undefined reference to `dht_read(dht_driver_t*, float*, float*)'
```

Atom code completion suggested me the functions but its still not working. How can I resolve this?

**Comment by eerimoq** [comment]
The easy fix is to wait for the official release of the DHT module. =)
