### ISSUE TITLE
CSTR conflicts with AVR #define CSTR    6

### ISSUE THREAD

**Issue by shacal** [eerimoq/simba#149]
As title says, simba redefines CSTR that is used in AVR io module (like: iotn1634.h).

**Comment by eerimoq** [comment]
I'm sorry, but I think we have to live with it. =/

**Comment by shacal** [comment]
Sure, just thinking that maybe document it...
I did some low level IO access and hit this problem, that was fixed by adjusting include orders.

**Comment by eerimoq** [comment]
Create a pull request if you have made improvements that can help others, that would be very welcome. =)
