### ISSUE TITLE
Is the new config system working as expected?

### ISSUE THREAD

**Issue by wingstar74** [eerimoq/simba#16]
Created a config.h file in root folder with the following content:
#ifndef __CONFIG_H__
#define __CONFIG_H__
/* Default system tick frequency. */
#ifndef CONFIG_SYSTEM_TICK_FREQUENCY
#    define CONFIG_SYSTEM_TICK_FREQUENCY 250
#endif 
#endif 

When running the frequency is still 100. Maybe I am missing something.

**Comment by eerimoq** [comment]
A fix is committed in e326a41e501a1ecced82618e9a877b702337596e. I didn't understand how c inclusion works... Sorry..

**Comment by wingstar74** [comment]
Now it works :-)

**Comment by eerimoq** [comment]
Wohoooo! =)
