### ISSUE TITLE
Wrong pin labels in image

### ISSUE THREAD

**Issue by lgenzelis** [eerimoq/simba#172]
In the image https://simba-os.readthedocs.io/en/15.0.3/_images/arduino-nano-pinout.png the MOSI and MISO pins are reversed. That is quite problematic, given that this image is one of the first results when one googles "arduino nano pinout".

**Comment by eerimoq** [comment]
Feel free to create a pull request with a correction and I'll merge.

**Comment by simonlbn** [comment]
FYI: This is fixed in the original version at
http://www.pighixxx.com/test/portfolio-items/nano/?portfolioID=314
