### ISSUE TITLE
Analog Write does not work on Arduino Nano

### ISSUE THREAD

**Issue by KeelyHill** [eerimoq/simba#175]
Running the [Analog Write example](http://simba-os.readthedocs.io/en/latest/examples/analog_write.html) on an Arduino Nano does not work. No voltage is emitted. All PWM tried. Tested with the Arduino IDE and library to check the board (and it works). No error codes are returned -- only zero. Writing a constant value (e.g. 1023) also fails.

I found a comment in [`.../arduino_nano/board.h`](https://github.com/eerimoq/simba/blob/b9f559ecf01e59fcc7fcc48244a9f970ace6d072/src/boards/arduino_nano/board.h#L84) saying d9 and d10 can't be used. But I want to clarify 3, 5, 6, & 11 also don't work.

**Comment by eerimoq** [comment]
I'll not have time to look into this. Sorry.

**Comment by KeelyHill** [comment]
No problem :) .  Thought I should at least report my findings.

**Comment by alberand** [comment]
I found the problem.
The **analog_output_pin_init** function initialize the pwm pin. Then, **analog_output_pin_write** configure duty cycle of the PWM module but doesn't set frequency (via setting compare register). The code for configuring compare register is placed at the **pwm_port_set_frequency** function.

The **pwm_start** function sets frequency + duty cycle (by calling **pwm_port_set_frequency**). So, by calling the pwm_start function between initialization and write fix the issue. 

I'm not sure where to place this call in the **analog_output_pin_init** or **analog_output_pin_write** with some handling if freq. is already set. Here is how I fixed it:

```
From 6094363622a48f683fe4dd8f836a89f856d7f744 Mon Sep 17 00:00:00 2001
From: alberand <albershteyn.andrey@gmail.com>
Date: Sun, 1 Jul 2018 14:47:19 +0200
Subject: [PATCH] Fix missing PWM frequency configuration for AVR port

---
 src/drivers/basic/analog_output_pin.c | 10 ++++++----
 1 file changed, 6 insertions(+), 4 deletions(-)

diff --git a/src/drivers/basic/analog_output_pin.c b/src/drivers/basic/analog_output_pin.c
index 5cf7d5ef..ef2e0c10 100644
--- a/src/drivers/basic/analog_output_pin.c
+++ b/src/drivers/basic/analog_output_pin.c
@@ -46,10 +46,12 @@ int analog_output_pin_init(struct analog_output_pin_t *self_p,
         return (-1);
     }
     
-    return (pwm_init(&self_p->pwm,
-                     pwm_p,
-                     pwm_frequency(10000),
-                     pwm_duty_cycle(0)));
+    pwm_init(&self_p->pwm,
+             pwm_p,
+             pwm_frequency(10000),
+             pwm_duty_cycle(0));
+
+    return (pwm_start(&self_p->pwm));
 }
 
 int analog_output_pin_write(struct analog_output_pin_t *self_p,
-- 
2.18.0

```

**Comment by eerimoq** [comment]
Create a pull request and I'll have a look.

**Comment by eerimoq** [comment]
Good find btw, The PWM module was refactored a few months ago, introducing the pwn_start-function. The analog module was not updated accordingly.
