### ISSUE TITLE
missing esptool.py

### ISSUE THREAD

**Issue by toomyem** [eerimoq/simba#185]
File _board.py_ for **esp01** board expects to find _esptool.py_ in _3pp/esptool_ directory, but there is only *binary* _esptool_.

```
esptool_path = os.path.join(os.environ["SIMBA_ROOT"],
                                "3pp",
                                "esptool",
                                "esptool.py") 
```

**Comment by eerimoq** [comment]
Unfortunately I don't remember why I replaced the python esptool with the compiled one. The commit message is not very descriptive. Looks like other boards are using the compiled tool. I must have forgotten to update the esp01 board.

**Comment by toomyem** [comment]
Maybe because for esp01 you are using boot_v1.4.bin and "write_flash" function?

**Comment by toomyem** [comment]
What's more, in board.mk you are using scripts for esp12:
```
BOARD_PY = $(SIMBA_ROOT)/src/boards/esp12e/board.py
RUN_PY ?= $(SIMBA_ROOT)/src/boards/esp12e/run.py
```

**Comment by toomyem** [comment]
In the "Hardware setup" section of the manual there is picture with description saying that there is esp01 in the test bed. So I thought that it is being tested and running.

Actually I was able to flash sample "hello world" type application but what I get are only boot messages, not a "hello" message I'm expecting. But this is another story which I have to take a closer look.

**Comment by eerimoq** [comment]
The test setup is a little dusty. Last time I used it was when the latest release was created, about a year ago. =)

**Comment by simonlbn** [comment]
FWIW, I think the better long term fix is to just switch to the official [esptool.py](https://github.com/espressif/esptool). I have been using it for a while since I frequently flash from a Raspberry Pi (IE. ARM) so the compiled esptool from Simba doesn't work.

As a bonus, the official esptool.py compress the image during transfer, so is generally faster than the esptool binary.

This has worked fine on all the ESP8266's I have tried.

**Comment by eerimoq** [comment]
Feel free to create a PR replacing the compiled program with the latest Python scripts. I can dust off some of my ESP boards to help out testing.

**Comment by toomyem** [comment]
I see you are already using esptool.py in esp-idf module, but it is not in newest version.
What do you think would be better. Just replace esptool in 3pp/esptool with esptool.py taken from Espressiff repository, or add this repository as submodule attached in 3pp/esptool directory?

**Comment by vijaygill** [comment]
Coming back after a few days ( got pulled away from projects at home by greater powers ), I see that this issue is being looked after by @toomyem (thanks!). I think this will resolve the issue I raised (and planned to work on a few weeks ago) #176.

**Comment by toomyem** [comment]
I guess we can close this issue now.

**Comment by eerimoq** [comment]
Thanks for the contribution, always appreciated increasing the quality of the project.
