### ISSUE TITLE
std_read()

### ISSUE THREAD

**Issue by alberand** [eerimoq/simba#201]
In the std lib there are plenty of different function for printing but there is not for reading.

Use case: if you have some simple application (with MININAL_CONFIG 0) you can use **std_printf()** but how to get input from user? You can use **uart_device_read()** but it requires **struct uart_device_t***

**Comment by eerimoq** [comment]
I would use `chan_read(sys_get_stdin(), ...)`.

**Comment by alberand** [comment]
Thanks!
But still, shouldn't it be there to make interface more self consistent

**Comment by eerimoq** [comment]
I usually use the shell module for a textual user interface. Which functions would you like to add?
