### ISSUE TITLE
platformio 3.0.1 says: simba framework doesn't support testing feature

### ISSUE THREAD

**Issue by wuwx** [eerimoq/simba#25]
```
cd project
mkdir test
pio test
```

how can i do with testing feature?

**Comment by eerimoq** [comment]
Personally I'm not using PlatformIO when developing simba applications, I'm using the make based build system, that is part of simba, to build and test my application and run unit tests. I'll have to take a look at the PlatformIO build system to understand why the test command fails and if it can be supported.

Is this feature important to you? I'll probably not implement it in the near future becuase there are other tasks that I want to finalize first.

**Comment by wuwx** [comment]
not important :)

**Comment by eerimoq** [comment]
Okay =)
