### ISSUE TITLE
esp12e support ext interrupt, but simba not define exti_device array

### ISSUE THREAD

**Issue by wuwx** [eerimoq/simba#28]
is there some quick method to use it ?

**Comment by eerimoq** [comment]
You can use the espressif interface directly, as Simba is a layer on top on the espressif RTOS. I've not implemented external interrupts in Simba on ESP yet.

If the interest for using Simba increases I'll implement all requested features for sure. Unless someone else implements it and sends a pull request. :) That would be appreciated :)

**Comment by wuwx** [comment]
i c, thanks :)
