### ISSUE TITLE
is necessary with FSTR in esp12e board

### ISSUE THREAD

**Issue by wuwx** [eerimoq/simba#36]
I found esp 12e has defined FSTR to a static char
simba library use many FSTR string, it cost about 10k+ mem
if i change FSTR to empty, the board is also work
so i don't understand why use FSTR

**Comment by wuwx** [comment]
i use this:

#define FSTR(s)  s

**Comment by eerimoq** [comment]
I'll do the same fix on the master branch. Thanks.

**Comment by eerimoq** [comment]
Implemented and pushed. String literals are now put in the ``.rodata`` section. It does not save any RAM because both ``.rodata`` and ``.data`` sections are mapped to RAM.
