### ISSUE TITLE
how to set remote server addr and port when use mqtt_client

### ISSUE THREAD

**Issue by wuwx** [eerimoq/simba#55]
simba project has mqtt_client
in path: src/inet/mqtt_client.c
i read test code try understand how to use it
but i not found how to set remote server addr and port

**Comment by eerimoq** [comment]
Create a TCP socket and pass a reference of it as ``chout_p`` and ``chin_p`` in ``mqtt_client_init()``.

https://github.com/eerimoq/simba/blob/master/src/inet/mqtt_client.h#L105-L126

Just for you information, the MQTT client module has only been tested by the unit test. It has not been tested with a real MQTT broker. Will be intresting to find out if it works in a real use case. If there is a problem I can fix it. I should write an MQTT example application that communicates with a real broker.
