### ISSUE TITLE
ESP32: I2C driver.

### ISSUE THREAD

**Issue by eerimoq** [eerimoq/simba#64]
Port the I2C driver to ESP32.

**Comment by cicamargoba** [comment]
Hello Erik
I want to port ADC to simba, this is possible using the espressif sdk (I mean espressif drivers) ?

**Comment by eerimoq** [comment]
The ESP8266 ADC driver port calls the Espressif SDK driver, and it works for single sample convertions. I've not seen the ESP32 Espressif driver API, so I don't have a good answer, but it will probably work :)

**Comment by cicamargoba** [comment]
Hello Erik
One question:

I understand that I need to create a driver in
simba/src/drivers/ports/esp32/  right?

How can I use this new driver on microptthon?


Best regards


Carlos

**Comment by eerimoq** [comment]
As usual when someone asks about a new feature I cannot resist implementing it myself. =) I started reading the technical reference, the data sheet and some header files of the IDF, and started the ADC port to ESP32. No success reading analog pins so far, but unless there is a lot of non-documented features required it should be ready in a few days.

For Pumbaa (I guess you are intrested in this MicroPython port), the ADC driver wrapper is already in place. Just have to set CONFIG_PUMBAA_CLASS_ADC to 1 and add class_adc.c to the list of files to build for ESP32. And of course, update the simba submodule to a version including the ADC driver port.

**Comment by cicamargoba** [comment]
Very good for me :)
I'll be waiting for updates
Thanks a lot.

Carlos

**Comment by eerimoq** [comment]
Moving ADC discussion to #65.

**Comment by eerimoq** [comment]
Postponed.

**Comment by LupascuAndrei** [comment]
Hello there :D 
Any chance the i2c port will be done soon? 
Thank you in advance.

**Comment by eerimoq** [comment]
Hi,

I don't have the energy to looks into it at the moment. Too much going on already. =)
