### ISSUE TITLE
ESP32: DAC driver.

### ISSUE THREAD

**Issue by eerimoq** [eerimoq/simba#66]
Port the DAC driver to ESP32.

**Comment by urish** [comment]
First of all, thanks for the awesome Simba & Pumbaa projects! 

Regarding the DAC, I found the following code which can hopefully help:

https://github.com/espressif/arduino-esp32/blob/758553a786520b138307691e842e53b25606960b/cores/esp32/esp32-hal-dac.c

**Comment by eerimoq** [comment]
Implemented by calling the ESP-IDF functions. Only one sample per pin may be converted in a single call to the convert fucntions.
