### ISSUE TITLE
Forum signup broken

### ISSUE THREAD

**Issue by simonlbn** [eerimoq/simba#77]
Hi,

I tried to sign up at https://forum.simbaos.org/member.php, but when I do I just get an error on submit saying:

The image verification code that you entered was incorrect. Please enter the code exactly how it appears in the image.

I did fill out the "security question" and see no image verification.

Regards,
Simon

**Comment by eerimoq** [comment]
Try now. Changed to using Google reCaptcha.

**Comment by simonlbn** [comment]
Works now, thanks!
